comment:
  image:
    repository: j10i2/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: j10i2/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: j10i2/ui
    tag: latest
  service:
    externalPort: 9292
