global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_kosykh'
