global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_kosykh'
