version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
     backnet:
      aliases:
       - post_db
       - comment_db
    env_file: .env



  ui:
    env_file: .env
    image: ${USERNAME}/ui
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    env_file: .env
    image: ${USERNAME}/post
    networks:
      - front_net
      - backnet


  comment:
    env_file: .env
    image: ${USERNAME}/comment
    networks:
      - front_net
      - backnet


  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - backnet

  mongodb_exporter:
    image: ${USERNAME}/mongodb_exporter
    environment:
      MONGODB_URI: "mongodb://post_db:27017"
    networks:
      - front_net
      - backnet

  blackbox-exporter:
    image: ${USERNAME}/blackbox_exporter
    networks:
      - front_net




volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    driver: bridge
  backnet:
    driver: bridge
