version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
     backnet:
      aliases:
       - post_db
       - comment_db
    env_file: .env

  ui:
    env_file: .env
    image: ${USERNAME}/ui
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - front_net

  post:
    env_file: .env
    image: ${USERNAME}/post
    networks:
      - front_net
      - backnet


  comment:
    env_file: .env
    image: ${USERNAME}/comment
    networks:
      - front_net
      - backnet

volumes:
  post_db:

networks:
  front_net:
    driver: bridge
  backnet:
    driver: bridge
