version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - front_net
      - backnet

  elasticsearch:
    image: elasticsearch:7.4.0
    environment:
      # single-node mode for testing and development
      # production mode requires many settings to be configured
      - discovery.type=single-node
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - front_net
      - backnet

  kibana:
    image: kibana:7.4.0
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "5601:5601"
    networks:
      - front_net
      - backnet


  zipkin:
    image: openzipkin/zipkin
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - "9411:9411"
    networks:
      - front_net
      - backnet



networks:
  front_net:
    driver: bridge
  backnet:
    driver: bridge
