version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
     backnet:
      aliases:
       - post_db
       - comment_db
    env_file: .env



  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - 1111:9292/tcp
    networks:
      - front_net
    env_file: .env
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - front_net
      - backnet
    env_file: .env
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - front_net
      - backnet
    env_file: .env


volumes:
  post_db:

networks:
  front_net:
    driver: bridge
  backnet:
    driver: bridge
